In [7]:
import csv
from datetime import datetime

In [8]:
def read_logs(file_path):
    """
    Lee un archivo CSV de logs y devuelve una lista de entradas de logs.

    :param file_path: Ruta del archivo de logs CSV.
    :return: Lista de tuplas (timestamp, level, device, event).
    """
    log_entries = []

    # Abrir el archivo CSV y leer las líneas
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        next(reader)  # Saltar la cabecera del CSV

        # Procesar cada línea del archivo CSV
        for row in reader:
            timestamp_str, level, device, event = row
            # Convertir el string de timestamp a un objeto datetime
            timestamp = datetime.strptime(timestamp_str, '%Y-%m-%d %H:%M:%S')
            # Añadir la entrada de log a la lista
            log_entries.append((timestamp, level, device, event))
    
    return log_entries

In [20]:
print(read_logs('logs.csv'))

[(datetime.datetime(2024, 6, 1, 12, 0, 1), ' INFO', ' Router1', ' Link Up'), (datetime.datetime(2024, 6, 1, 12, 5, 42), ' ERROR', ' Router2', ' Link Down'), (datetime.datetime(2024, 6, 1, 12, 7, 55), ' WARN', ' Switch3', ' High CPU Usage'), (datetime.datetime(2024, 6, 1, 12, 10), ' INFO', ' Router1', ' Link Down'), (datetime.datetime(2024, 6, 1, 12, 15, 10), ' INFO', ' Router2', ' Link Up'), (datetime.datetime(2024, 6, 1, 12, 20, 33), ' INFO', ' Router3', ' Link Down'), (datetime.datetime(2024, 6, 1, 12, 22, 21), ' ERROR', ' Router1', ' Link Down'), (datetime.datetime(2024, 6, 1, 12, 30, 42), ' INFO', ' Router3', ' Link Up'), (datetime.datetime(2024, 6, 1, 12, 32, 15), ' WARN', ' Switch2', ' High Memory Usage'), (datetime.datetime(2024, 6, 1, 12, 35, 20), ' INFO', ' Router2', ' Link Down')]

In [11]:
import pandas as pd

In [12]:
df_logs = pd.read_csv('logs.csv')

In [13]:
print(df_logs)

                 Fecha    Tipo    Device                Link
0  2024-06-01 12:00:01    INFO   Router1             Link Up
1  2024-06-01 12:05:42   ERROR   Router2           Link Down
2  2024-06-01 12:07:55    WARN   Switch3      High CPU Usage
3  2024-06-01 12:10:00    INFO   Router1           Link Down
4  2024-06-01 12:15:10    INFO   Router2             Link Up
5  2024-06-01 12:20:33    INFO   Router3           Link Down
6  2024-06-01 12:22:21   ERROR   Router1           Link Down
7  2024-06-01 12:30:42    INFO   Router3             Link Up
8  2024-06-01 12:32:15    WARN   Switch2   High Memory Usage
9  2024-06-01 12:35:20    INFO   Router2           Link Down

In [14]:
df_logs.head()

                 Fecha    Tipo    Device             Link
0  2024-06-01 12:00:01    INFO   Router1          Link Up
1  2024-06-01 12:05:42   ERROR   Router2        Link Down
2  2024-06-01 12:07:55    WARN   Switch3   High CPU Usage
3  2024-06-01 12:10:00    INFO   Router1        Link Down
4  2024-06-01 12:15:10    INFO   Router2          Link Up

In [15]:
df_logs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Fecha    10 non-null     object
 1    Tipo    10 non-null     object
 2    Device  10 non-null     object
 3    Link    10 non-null     object
dtypes: object(4)
memory usage: 452.0+ bytes

In [17]:
df_logs.tail()

                 Fecha    Tipo    Device                Link
5  2024-06-01 12:20:33    INFO   Router3           Link Down
6  2024-06-01 12:22:21   ERROR   Router1           Link Down
7  2024-06-01 12:30:42    INFO   Router3             Link Up
8  2024-06-01 12:32:15    WARN   Switch2   High Memory Usage
9  2024-06-01 12:35:20    INFO   Router2           Link Down

In [18]:
df_logs.count()

Fecha      10
 Tipo      10
 Device    10
 Link      10
dtype: int64

In [19]:
df_logs.describe()

                      Fecha   Tipo    Device        Link
count                    10     10        10          10
unique                   10      3         5           4
top     2024-06-01 12:00:01   INFO   Router1   Link Down
freq                      1      6         3           5